# Generated by scripts/gen-packages.ts — do not edit by hand.
class ProjectBrain < Formula
  desc "Local-first MCP server for codebase knowledge: semantic search plus a call graph"
  homepage "https://github.com/jcsoftdev/project-brain"
  version "0.36.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/jcsoftdev/project-brain/releases/download/v0.36.0/project-brain-darwin-arm64"
      sha256 "702fda69fcd9198fe8007bb138cd66b7af3293b6697c23cfb151dcb4998ad2f8"
    end
    # Intel macOS has no published binary — see the build matrix in release.yml.
  end

  on_linux do
    on_intel do
      url "https://github.com/jcsoftdev/project-brain/releases/download/v0.36.0/project-brain-linux-x64"
      sha256 "40db1f05bc107210c0da5caa79acb22c829ad9953c82aaf4d54ee28ee1484bdf"
    end
    on_arm do
      url "https://github.com/jcsoftdev/project-brain/releases/download/v0.36.0/project-brain-linux-arm64"
      sha256 "e7e88b1fb5107ed1a18e305369bee762020e697fdce22dd947150ce0a4c256f9"
    end
  end

  def install
    bin.install Dir["project-brain-*"].first => "project-brain"
  end

  def caveats
    <<~EOS
      Register the MCP server and install the host skills:
        project-brain setup

      Then, in a project:
        project-brain init
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/project-brain --version")
  end
end
