# Generated by scripts/gen-packages.ts — do not edit by hand.
class ProjectBrain < Formula
  desc "Local-first MCP server for codebase knowledge: semantic search plus a call graph"
  homepage "https://github.com/jcsoftdev/project-brain"
  version "0.26.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/jcsoftdev/project-brain/releases/download/v0.26.0/project-brain-darwin-arm64"
      sha256 "7c03b06672c17a0dfad5b8ce0581d599a9f7407f26a4a410e811e70a6cfbe55a"
    end
    # Intel macOS has no published binary — see the build matrix in release.yml.
  end

  on_linux do
    on_intel do
      url "https://github.com/jcsoftdev/project-brain/releases/download/v0.26.0/project-brain-linux-x64"
      sha256 "d08c5aa84a3aba6cbb0718d4f1f56a0507f2ed7a339c950bf88092e65d5deb16"
    end
    on_arm do
      url "https://github.com/jcsoftdev/project-brain/releases/download/v0.26.0/project-brain-linux-arm64"
      sha256 "dc9d2a2d700170f1ebc1e651ad972b5e917090563c4d48befeb601db08575ff9"
    end
  end

  def install
    bin.install Dir["project-brain-*"].first => "project-brain"
  end

  def caveats
    <<~EOS
      Register the MCP server and install the host skills:
        project-brain setup

      Then, in a project:
        project-brain init
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/project-brain --version")
  end
end
